version: 2
updates:
  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
  # Check for updates to NuGet packages every week
  - package-ecosystem: "nuget"
    directories:
    - "/test/JsBind.Net.Tests/"
    - "/test/JsBind.Net.TestsRunner/"
    allow:
    - dependency-type: "direct"
    ignore:
    - dependency-name: "Microsoft.JSInterop"
    - dependency-name: "Microsoft.Extensions.DependencyInjection.Abstractions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      aspnetcore:
        patterns: [ Microsoft.AspNetCore.* ]
      mstest:
        patterns: [ MSTest.* ]
  - package-ecosystem: "npm"
    directory: "/src/JsBind.Net/content/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
